In [1]:
!pip install financedatabase
!pip install yfinance
!pip install --upgrade financedatabase

Requirement already satisfied: financedatabase in /Users/daniel/anaconda3/lib/python3.10/site-packages (2.1.0)
Requirement already satisfied: pandas in /Users/daniel/anaconda3/lib/python3.10/site-packages (from financedatabase) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from pandas->financedatabase) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from pandas->financedatabase) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from pandas->financedatabase) (1.23.5)
Requirement already satisfied: six>=1.5 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas->financedatabase) (1.16.0)
Requirement already satisfied: yfinance in /Users/daniel/anaconda3/lib/python3.10/site-packages (0.2.18)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from yfinance) (4.11.1)
Requirement already satisfied: pandas>=1.3.0 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from yfinance) (1.5.3)
Requirement already satisfied: cryptography>=3.3.2 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from yfinance) (39.0.1)
Requirement already satisfied: lxml>=4.9.1 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from yfinance) (4.9.1)
Requirement already satisfied: multitasking>=0.0.7 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from yfinance) (0.0.11)
Requirement already satisfied: appdirs>=1.4.4 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from yfinance) (1.4.4)
Requirement already satisfied: requests>=2.26 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from yfinance) (2.28.1)
Requirement already satisfied: numpy>=1.16.5 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from yfinance) (1.23.5)
Requirement already satisfied: frozendict>=2.3.4 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from yfinance) (2.3.8)
Requirement already satisfied: pytz>=2022.5 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from yfinance) (2022.7)
Requirement already satisfied: html5lib>=1.1 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.2.post1)
Requirement already satisfied: cffi>=1.12 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from cryptography>=3.3.2->yfinance) (1.15.1)
Requirement already satisfied: six>=1.9 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /Users/daniel/anaconda3/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from requests>=2.26->yfinance) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from requests>=2.26->yfinance) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from requests>=2.26->yfinance) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in /Users/daniel/anaconda3/lib/python3.10/site-packages (from requests>=2.26->yfinance) (3.4)
Requirement already satisfied: pycparser in /Users/daniel/anaconda3/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)

In [5]:
import yfinance as yf
Stocks = ["FRDAX", "PRILX", "PRDGX",
                  "CCCRX", "JENIX", "FGIKX", "MFRCX", "LMMRX", 
                  "JDEUX", "JGICX", "MRGAX", "NSBFX", "ITHSX",
          "VTI", "VOO", "SPY", "IVV", "VIG",
                  "ITOT", "RSP", "SCHX", "SPLG", 
                  "GSLC", "FTCS"]

#Download stock data
Stocks = yf.download(Stocks, start="2016-01-01", end="2023-04-30")

#only close
adj_close_stocks = Stocks.xs('Adj Close', level=0, axis=1)

# Define the desired column order
desired_columns = ["FRDAX", "PRILX", "PRDGX",
                  "CCCRX", "JENIX", "FGIKX", "MFRCX", "LMMRX", 
                  "JDEUX", "JGICX", "MRGAX", "NSBFX", "ITHSX",
                  "VTI", "VOO", "SPY", "IVV", "VIG",
                  "ITOT", "RSP", "SCHX", "SPLG", 
                  "GSLC", "FTCS"]

# Reorder the columns in the dataframe
adj_close_stocks = adj_close_stocks.reindex(columns=desired_columns)

# Print the dataframe with only 'Adj Close'
adj_close_stocks

[*********************100%***********************]  24 of 24 completed

,FRDAX,PRILX,PRDGX,CCCRX,JENIX,FGIKX,MFRCX,LMMRX,JDEUX,JGICX,...,VOO,SPY,IVV,VIG,ITOT,RSP,SCHX,SPLG,GSLC,FTCS
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-04,35.795307,21.595482,28.289228,12.559057,22.515039,22.335350,20.309053,12.609809,13.374409,30.352087,...,161.455673,176.563599,177.615921,66.604202,40.280571,66.903496,21.101311,20.461603,36.678505,34.278030
2016-01-05,35.871403,21.595482,28.364487,12.565133,22.596685,22.335350,20.365152,12.650182,13.380619,30.443708,...,161.744751,176.862213,177.985214,66.821228,40.351028,67.062363,21.145409,20.630169,36.757378,34.515182
2016-01-06,35.369171,21.364735,28.004913,12.395085,22.301502,21.928110,20.115810,12.522337,13.169604,30.034971,...,159.694916,174.631241,175.655121,66.013847,39.778606,65.835358,20.871992,20.323694,36.328934,34.141205
2016-01-07,34.661480,20.861826,27.402838,12.097506,21.874439,21.325087,19.679459,12.280100,12.840677,29.309109,...,155.805481,170.441528,171.452103,64.798439,38.823109,64.343521,20.373674,19.944977,35.602886,33.402367
2016-01-08,34.227741,20.678413,27.110153,11.963900,21.623228,21.074478,19.436348,12.179165,12.679312,28.984947,...,154.149826,168.570633,169.552841,64.129982,38.365181,63.557861,20.144360,19.761095,35.136791,33.001030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-24,86.599998,51.000000,66.410004,26.719999,57.689999,50.759998,42.290001,27.370001,31.680000,65.379997,...,379.089996,412.630005,414.410004,156.889999,90.970001,145.190002,48.650002,48.520000,81.800003,73.860001
2023-04-25,85.300003,50.259998,65.459999,26.290001,56.939999,49.889999,41.619999,27.049999,31.160000,64.339996,...,373.100006,406.079987,407.829987,154.990005,89.419998,142.720001,47.849998,47.750000,80.529999,73.089996
2023-04-26,84.889999,50.060001,64.959999,26.190001,56.810001,49.669998,41.549999,26.870001,31.070000,64.099998,...,371.440002,404.359985,406.170013,153.669998,89.029999,141.229996,47.669998,47.560001,80.190002,72.070000
2023-04-27,86.120003,50.810001,65.879997,26.770000,57.770000,50.380001,42.320000,27.320000,31.709999,65.330002,...,378.809998,412.410004,414.230011,156.190002,90.690002,143.550003,48.580002,48.470001,81.690002,73.029999
2023-04-28,86.790001,51.299999,66.500000,26.969999,58.299999,50.860001,42.630001,27.590000,32.000000,65.930000,...,382.049988,415.929993,417.660004,157.570007,91.470001,145.139999,48.990002,48.900002,82.349998,73.529999

In [14]:
import yfinance as yf

#Define tickers
ticker_mf = ["FRDAX", "PRILX", "PRDGX", 
                  "CCCRX", "JENIX", "FGIKX", "MFRCX", "LMMRX", 
                  "JDEUX", "JGICX", "MRGAX", "NSBFX", "ITHSX"]
         
ticker_etf = ["VTI", "VOO", "SPY", "IVV", "VIG",
                  "ITOT", "RSP", "SCHX", "SPLG", 
                  "GSLC", "FTCS"]

In [8]:
# Assign dates
start_date_normal = '2016-01-04'
end_date_normal = '2019-12-31'
start_date_crisis = '2020-01-01'
end_date_crisis = '2023-04-28'

In [11]:
import pandas_datareader as pdr
import numpy as np

# Define the Treasury rate series code
treasury_rate_series = 'DGS1'

# Download Treasury rates
treasury_rates = pdr.get_data_fred(treasury_rate_series, start_date_normal, end_date_crisis)

# Print the downloaded data
rf_yearly = treasury_rates/100
rf_yearly = rf_yearly.dropna()
rf_daily = np.exp(rf_yearly / 252) - 1
rf_daily

                DGS1
DATE
2016-01-04  0.000024
2016-01-05  0.000027
2016-01-06  0.000027
2016-01-07  0.000026
2016-01-08  0.000025
...              ...
2023-04-24  0.000189
2023-04-25  0.000183
2023-04-26  0.000184
2023-04-27  0.000190
2023-04-28  0.000190

[1832 rows x 1 columns]

In [18]:
daily_returns = adj_close_stocks.pct_change()
daily_returns = daily_returns.iloc[1:]
daily_returns

,FRDAX,PRILX,PRDGX,CCCRX,JENIX,FGIKX,MFRCX,LMMRX,JDEUX,JGICX,...,VOO,SPY,IVV,VIG,ITOT,RSP,SCHX,SPLG,GSLC,FTCS
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-05,0.002126,0.000000,0.002660,0.000484,0.003626,0.000000,0.002762,0.003202,0.000464,0.003019,...,0.001790,0.001691,0.002079,0.003258,0.001749,0.002375,0.002090,0.008238,0.002150,0.006918
2016-01-06,-0.014001,-0.010685,-0.012677,-0.013533,-0.013063,-0.018233,-0.012244,-0.010106,-0.015770,-0.013426,...,-0.012673,-0.012614,-0.013091,-0.012083,-0.014186,-0.018296,-0.012930,-0.014856,-0.011656,-0.010835
2016-01-07,-0.020009,-0.023539,-0.021499,-0.024008,-0.019150,-0.027500,-0.021692,-0.019344,-0.024976,-0.024167,...,-0.024355,-0.023992,-0.023928,-0.018411,-0.024020,-0.022660,-0.023875,-0.018634,-0.019985,-0.021641
2016-01-08,-0.012514,-0.008792,-0.010681,-0.011044,-0.011484,-0.011752,-0.012354,-0.008219,-0.012567,-0.011060,...,-0.010626,-0.010977,-0.011078,-0.010316,-0.011795,-0.012210,-0.011255,-0.009219,-0.013091,-0.012015
2016-01-11,-0.001779,0.002575,-0.001234,-0.000508,0.001452,-0.004459,-0.001924,0.001657,-0.000979,-0.000243,...,0.000114,0.000990,0.001037,0.002166,-0.000230,-0.003195,-0.000219,-0.004431,0.002781,-0.000829
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-24,0.002895,-0.000784,0.001961,0.001124,0.000347,0.002964,0.000947,0.001464,0.000632,-0.000306,...,0.001321,0.001043,0.001256,0.002236,0.000440,0.001863,0.000617,0.001032,0.001224,0.003396
2023-04-25,-0.015011,-0.014510,-0.014305,-0.016093,-0.013001,-0.017139,-0.015843,-0.011692,-0.016414,-0.015907,...,-0.015801,-0.015874,-0.015878,-0.012110,-0.017039,-0.017012,-0.016444,-0.015870,-0.015526,-0.010425
2023-04-26,-0.004807,-0.003979,-0.007638,-0.003804,-0.002283,-0.004410,-0.001682,-0.006654,-0.002888,-0.003730,...,-0.004449,-0.004236,-0.004070,-0.008517,-0.004361,-0.010440,-0.003762,-0.003979,-0.004222,-0.013955
2023-04-27,0.014489,0.014982,0.014163,0.022146,0.016898,0.014294,0.018532,0.016747,0.020599,0.019189,...,0.019842,0.019908,0.019844,0.016399,0.018645,0.016427,0.019090,0.019134,0.018706,0.013320
2023-04-28,0.007780,0.009644,0.009411,0.007471,0.009174,0.009528,0.007325,0.009883,0.009145,0.009184,...,0.008553,0.008535,0.008280,0.008835,0.008601,0.011076,0.008440,0.008871,0.008079,0.006847

In [19]:
print(daily_returns.columns)

Index(['FRDAX', 'PRILX', 'PRDGX', 'CCCRX', 'JENIX', 'FGIKX', 'MFRCX', 'LMMRX',
       'JDEUX', 'JGICX', 'MRGAX', 'NSBFX', 'ITHSX', 'VTI', 'VOO', 'SPY', 'IVV',
       'VIG', 'ITOT', 'RSP', 'SCHX', 'SPLG', 'GSLC', 'FTCS'],
      dtype='object')

In [22]:
import pandas as pd

# First, let's isolate the relevant data
etf_df = daily_returns[ticker_etf].copy()
mf_df = daily_returns[ticker_mf].copy()

# Then, create equally weighted portfolio returns
etf_portfolio_returns = etf_df.mean(axis=1)
mf_portfolio_returns = mf_df.mean(axis=1)

Date
2016-01-05    0.003143
2016-01-06   -0.013329
2016-01-07   -0.022365
2016-01-08   -0.011271
2016-01-11   -0.000221
                ...
2023-04-24    0.001347
2023-04-25   -0.015332
2023-04-26   -0.006046
2023-04-27    0.018190
2023-04-28    0.008620
Length: 1842, dtype: float64

In [29]:
import yfinance as yf

# Download S&P 500 data (only Adj Close) from 2016 to present
ticker = '^SP500TR'  # Ticker symbol for S&P 500
start_date = '2016-01-01'
end_date = '2023-04-29'
sp500_adjclose = yf.download(ticker, start=start_date, end=end_date)['Adj Close']
sp500_returns = sp500_adjclose.pct_change().dropna()
sp500_returns

[*********************100%***********************]  1 of 1 completed

Date
2016-01-05    0.002014
2016-01-06   -0.012761
2016-01-07   -0.023674
2016-01-08   -0.010833
2016-01-11    0.000851
                ...
2023-04-24    0.000852
2023-04-25   -0.015769
2023-04-26   -0.003836
2023-04-27    0.019591
2023-04-28    0.008361
Name: Adj Close, Length: 1842, dtype: float64

In [30]:
rf_daily_aligned = rf_daily.reindex(daily_returns.index)
etf_excess_returns = etf_portfolio_returns.sub(rf_daily_aligned['DGS1'], axis=0)  
mf_excess_returns = mf_portfolio_returns.sub(rf_daily_aligned['DGS1'], axis=0)
sp500_excess_returns = sp500_returns.sub(rf_daily_aligned['DGS1'], axis=0)
sp500_excess_returns

Date
2016-01-05    0.001987
2016-01-06   -0.012788
2016-01-07   -0.023701
2016-01-08   -0.010858
2016-01-11    0.000826
                ...
2023-04-24    0.000663
2023-04-25   -0.015951
2023-04-26   -0.004020
2023-04-27    0.019401
2023-04-28    0.008170
Length: 1842, dtype: float64

In [39]:
normal_sp500_excess_returns = sp500_excess_returns.loc[start_date_normal:end_date_normal]
normal_etf_excess_returns = etf_excess_returns.loc[start_date_normal:end_date_normal]
crisis_sp500_excess_returns = sp500_excess_returns.loc[start_date_crisis:end_date_crisis]
crisis_etf_excess_returns = etf_excess_returns.loc[start_date_crisis:end_date_crisis]

In [64]:
# Filter your returns
normal_sp500_excess_returns = sp500_excess_returns.loc[start_date_normal:end_date_normal]
normal_etf_excess_returns = etf_excess_returns.loc[start_date_normal:end_date_normal]

combined_returns = pd.concat([normal_sp500_excess_returns, normal_etf_excess_returns], axis=1).dropna()

# Perform linear regression to calculate beta and intercept
slope, intercept, r_value, p_value, std_err = stats.linregress(combined_returns.iloc[:, 0], combined_returns.iloc[:, 1])

# Store the results in a DataFrame
CAPM_etf_normal = pd.DataFrame({'Fund': ['ETF Normal'], 'Beta': [slope], 'Alpha': [intercept], 
                      'R-Squared': [r_value], 'p-value': [p_value], 'Std Error': [std_err]})
CAPM_etf_normal

         Fund      Beta     Alpha  R-Squared  p-value  Std Error
0  ETF Normal  0.970796 -0.000002   0.996078      0.0   0.002732

In [46]:
# Filter your returns
crisis_sp500_excess_returns = sp500_excess_returns.loc[start_date_crisis:end_date_crisis]
crisis_etf_excess_returns = etf_excess_returns.loc[start_date_crisis:end_date_crisis]

combined_returns = pd.concat([crisis_sp500_excess_returns, crisis_etf_excess_returns], axis=1).dropna()

# Perform linear regression to calculate beta and intercept
slope, intercept, r_value, p_value, std_err = stats.linregress(combined_returns.iloc[:, 0], combined_returns.iloc[:, 1])

# Store the results in a DataFrame
CAPM_etf_crisis = pd.DataFrame({'Fund': ['ETF Crisis'], 'Beta': [slope], 'Alpha': [intercept], 
                      'R-Squared': [r_value], 'p-value': [p_value], 'Std Error': [std_err]})
CAPM_etf_crisis

         Fund      Beta     Alpha  R-Squared  p-value  Std Error
0  ETF Crisis  0.968506 -0.000008    0.99777      0.0    0.00225

In [48]:
# Filter your returns
normal_sp500_excess_returns = sp500_excess_returns.loc[start_date_normal:end_date_normal]
normal_mf_excess_returns = mf_excess_returns.loc[start_date_normal:end_date_normal]

combined_returns = pd.concat([normal_sp500_excess_returns, normal_mf_excess_returns], axis=1).dropna()

# Perform linear regression to calculate beta and intercept
slope, intercept, r_value, p_value, std_err = stats.linregress(combined_returns.iloc[:, 0], combined_returns.iloc[:, 1])

# Store the results in a DataFrame
CAPM_mf_normal = pd.DataFrame({'Fund': ['MF Normal'], 'Beta': [slope], 'Alpha': [intercept], 
                      'R-Squared': [r_value], 'p-value': [p_value], 'Std Error': [std_err]})
CAPM_mf_normal

        Fund      Beta     Alpha  R-Squared  p-value  Std Error
0  MF Normal  0.940768  0.000011   0.993397      0.0   0.003443

In [52]:
# Filter your returns
crisis_sp500_excess_returns = sp500_excess_returns.loc[start_date_crisis:end_date_crisis]
crisis_mf_excess_returns = mf_excess_returns.loc[start_date_crisis:end_date_crisis]

combined_returns = pd.concat([crisis_sp500_excess_returns, crisis_mf_excess_returns], axis=1).dropna()

# Perform linear regression to calculate beta and intercept
slope, intercept, r_value, p_value, std_err = stats.linregress(combined_returns.iloc[:, 0], combined_returns.iloc[:, 1])

# Store the results in a DataFrame
CAPM_mf_crisis = pd.DataFrame({'Fund': ['MF Crisis'], 'Beta': [slope], 'Alpha': [intercept], 
                      'R-Squared': [r_value], 'p-value': [p_value], 'Std Error': [std_err]})
CAPM_mf_crisis

        Fund      Beta         Alpha  R-Squared  p-value  Std Error
0  MF Crisis  0.943064 -2.329715e-07   0.994428      0.0   0.003472

In [53]:
CAPM_mf_normal.to_clipboard()

In [70]:
import pandas_datareader.data as web
# Retrieve SMB data from the Kenneth R. French Data Library
smbhml_data_crisis = web.DataReader('F-F_Research_Data_5_Factors_2x3_daily', 'famafrench', start_date_crisis, end_date_crisis)
SMB_crisis = smbhml_data_crisis[0]['SMB']
HML_crisis = smbhml_data_crisis[0]['HML']
smbhml_data_normal = web.DataReader('F-F_Research_Data_5_Factors_2x3_daily', 'famafrench', start_date_normal, end_date_normal)
SMB_normal = smbhml_data_normal[0]['SMB']
HML_normal = smbhml_data_normal[0]['HML']
SMB_normal = SMB_normal.iloc[1:]
HML_normal = HML_normal.iloc[1:]

In [62]:
import statsmodels.api as sm

# Prepare the factors data and the excess returns data
X_crisis = sm.add_constant(pd.concat([SMB_crisis, HML_crisis, crisis_sp500_excess_returns], axis=1))
y_crisis = crisis_etf_excess_returns

# Run the regression
model = sm.OLS(y_crisis, X_crisis, missing='drop').fit()

# Create a DataFrame to store the results
FF3_etf_crisis = pd.DataFrame({
    'Fund': ['ETF Crisis'],
    'Alpha': [model.params.const],
    'Beta (Market)': [model.params.iloc[1]],
    'Beta (SMB)': [model.params.iloc[2]],
    'Beta (HML)': [model.params.iloc[3]],
    'R-Squared': [model.rsquared],
})

FF3_etf_crisis

         Fund     Alpha  Beta (Market)  Beta (SMB)  Beta (HML)  R-Squared
0  ETF Crisis -0.000008       0.000287     0.00027    0.966634   0.996643

In [69]:
HML_normal

Date
2016-01-04    0.52
2016-01-05    0.01
2016-01-06    0.00
2016-01-07    0.08
2016-01-08   -0.03
              ...
2019-12-24   -0.01
2019-12-26    0.00
2019-12-27   -0.07
2019-12-30    0.56
2019-12-31    0.11
Name: HML, Length: 1006, dtype: float64

In [100]:
import statsmodels.api as sm

# Prepare the factors data and the excess returns data
X_normal = sm.add_constant(pd.concat([SMB_normal, HML_normal, normal_sp500_excess_returns], axis=1))
y_normal = normal_etf_excess_returns

# Run the regression
model = sm.OLS(y_normal, X_normal, missing='drop').fit()

# Create a DataFrame to store the results
FF3_etf_normal = pd.DataFrame({
    'Fund': ['ETF Normal'],
    'Alpha': [model.params.const],
    'Beta (Market)': [model.params.iloc[1]],
    'Beta (SMB)': [model.params.iloc[2]],
    'Beta (HML)': [model.params.iloc[3]],
    'R-Squared': [model.rsquared],
})
# Extract the p-values of the factor coefficients
p_values = model.pvalues[1:]  # Exclude the constant term
alpha_p_value = model.pvalues[0]

# Check the significance of each factor
significant_factors = [factor for factor, p_value in zip(['Market', 'SMB', 'HML'], p_values) if p_value < 0.05]

# Check the significance of alpha
is_alpha_significant = alpha_p_value < 0.05

# Print the significant factors and alpha significance
print("Significant Factors:")
for factor in significant_factors:
    print(factor)

print("Alpha Significance: ", "Significant" if is_alpha_significant else "Not Significant")


FF3_etf_normal

Significant Factors:
Market
SMB
HML
Alpha Significance:  Significant

         Fund     Alpha  Beta (Market)  Beta (SMB)  Beta (HML)  R-Squared
0  ETF Normal  0.000002        0.00041   -0.000086    0.967076   0.992853

In [97]:
import statsmodels.api as sm

# Prepare the factors data and the excess returns data
X_crisis = sm.add_constant(pd.concat([SMB_crisis, HML_crisis, crisis_sp500_excess_returns], axis=1))
y_crisis = crisis_etf_excess_returns

# Run the regression
model = sm.OLS(y_crisis, X_crisis, missing='drop').fit()

# Create a DataFrame to store the results
FF3_etf_crisis = pd.DataFrame({
    'Fund': ['ETF Crisis'],
    'Alpha': [model.params.const],
    'Beta (Market)': [model.params.iloc[1]],
    'Beta (SMB)': [model.params.iloc[2]],
    'Beta (HML)': [model.params.iloc[3]],
    'R-Squared': [model.rsquared],
})
# Extract the p-values of the factor coefficients
p_values = model.pvalues[1:]  # Exclude the constant term
alpha_p_value = model.pvalues[0]

# Check the significance of each factor
significant_factors = [factor for factor, p_value in zip(['Market', 'SMB', 'HML'], p_values) if p_value < 0.05]

# Check the significance of alpha
is_alpha_significant = alpha_p_value < 0.05

# Print the significant factors and alpha significance
print("Significant Factors:")
for factor in significant_factors:
    print(factor)

print("Alpha Significance: ", "Significant" if is_alpha_significant else "Not Significant")

FF3_etf_crisis

Significant Factors:
Market
SMB
HML
Alpha Significance:  Significant

         Fund     Alpha  Beta (Market)  Beta (SMB)  Beta (HML)  R-Squared
0  ETF Crisis -0.000008       0.000287     0.00027    0.966634   0.996643

In [98]:
import statsmodels.api as sm

# Prepare the factors data and the excess returns data
X_normal = sm.add_constant(pd.concat([SMB_normal, HML_normal, normal_sp500_excess_returns], axis=1))
y_normal = normal_mf_excess_returns

# Run the regression
model = sm.OLS(y_normal, X_normal, missing='drop').fit()

# Create a DataFrame to store the results
FF3_mf_normal = pd.DataFrame({
    'Fund': ['MF Normal'],
    'Alpha': [model.params.const],
    'Beta (Market)': [model.params.iloc[1]],
    'Beta (SMB)': [model.params.iloc[2]],
    'Beta (HML)': [model.params.iloc[3]],
    'R-Squared': [model.rsquared],
})

# Extract the p-values of the factor coefficients
p_values = model.pvalues[1:]  # Exclude the constant term
alpha_p_value = model.pvalues[0]

# Check the significance of each factor
significant_factors = [factor for factor, p_value in zip(['Market', 'SMB', 'HML'], p_values) if p_value < 0.05]

# Check the significance of alpha
is_alpha_significant = alpha_p_value < 0.05

# Print the significant factors and alpha significance
print("Significant Factors:")
for factor in significant_factors:
    print(factor)

print("Alpha Significance: ", "Significant" if is_alpha_significant else "Not Significant")

FF3_mf_normal

Significant Factors:
Market
SMB
HML
Alpha Significance:  Significant

        Fund     Alpha  Beta (Market)  Beta (SMB)  Beta (HML)  R-Squared
0  MF Normal  0.000014        0.00013    0.000137    0.940634   0.987031

In [99]:
import statsmodels.api as sm

# Prepare the factors data and the excess returns data
X_crisis = sm.add_constant(pd.concat([SMB_crisis, HML_crisis, crisis_sp500_excess_returns], axis=1))
y_crisis = crisis_mf_excess_returns

# Run the regression
model = sm.OLS(y_crisis, X_crisis, missing='drop').fit()

# Create a DataFrame to store the results
FF3_mf_crisis = pd.DataFrame({
    'Fund': ['MF Crisis'],
    'Alpha': [model.params.const],
    'Beta (Market)': [model.params.iloc[1]],
    'Beta (SMB)': [model.params.iloc[2]],
    'Beta (HML)': [model.params.iloc[3]],
    'R-Squared': [model.rsquared],
})

# Extract the p-values of the factor coefficients
p_values = model.pvalues[1:]  # Exclude the constant term
alpha_p_value = model.pvalues[0]

# Check the significance of each factor
significant_factors = [factor for factor, p_value in zip(['Market', 'SMB', 'HML'], p_values) if p_value < 0.05]

# Check the significance of alpha
is_alpha_significant = alpha_p_value < 0.05

# Print the significant factors and alpha significance
print("Significant Factors:")
for factor in significant_factors:
    print(factor)

print("Alpha Significance: ", "Significant" if is_alpha_significant else "Not Significant")


FF3_mf_crisis

Significant Factors:
SMB
HML
Alpha Significance:  Significant

        Fund     Alpha  Beta (Market)  Beta (SMB)  Beta (HML)  R-Squared
0  MF Crisis -0.000009      -0.000009    0.000533    0.944263   0.991166

In [80]:
FF3_mf_crisis.to_clipboard()

In [57]:
# Retrieve momentum data from the Kenneth R. French Data Library
momentum_data_crisis = web.DataReader('F-F_Momentum_Factor_daily', 'famafrench', start_date_crisis, end_date_crisis)
MOM_crisis = momentum_data_crisis[0]['Mom   ']
momentum_data_normal = web.DataReader('F-F_Momentum_Factor_daily', 'famafrench', start_date_normal, end_date_normal)
MOM_normal = momentum_data_crisis[0]['Mom   ']

In [67]:
df_results.to_clipboard(index=False, header=True)

In [81]:
normal_returns_df = pd.DataFrame({
    'Mutual Fund Excess Returns': normal_mf_excess_returns,
    'ETF Excess Returns': normal_etf_excess_returns
})

normal_returns_df.head()

            Mutual Fund Excess Returns  ETF Excess Returns
Date
2016-01-05                    0.001799            0.003116
2016-01-06                   -0.013911           -0.013356
2016-01-07                   -0.022871           -0.022391
2016-01-08                   -0.011421           -0.011297
2016-01-11                   -0.000335           -0.000246

In [84]:
# Create empty lists to store the results
stocks = []
alphas = []
betas = []
smb_coefs = []
hml_coefs = []
RSQ = []
alpha_pvalues = []

# Iterate over each stock
for stock in normal_returns_df.columns:
    # Remove rows with NaN values from both the stock and index returns
    combined_returns = pd.concat([normal_sp500_excess_returns, normal_returns_df[stock], SMB_normal, HML_normal], axis=1).dropna()
    
    # Check if the combined_returns DataFrame is empty
    if combined_returns.empty:
        # Handle empty DataFrame case (e.g., by assigning NaN values to coefficients)
        alpha, beta, smb_coef, hml_coef, constant = (float('NaN'),) * 5
        alpha_pvalue = float('NaN')
    else:
        # Perform linear regression to calculate coefficients
        Y = combined_returns.iloc[:, 1]
        X = combined_returns.iloc[:, [0, 2, 3]]
        X = sm.add_constant(X)
        model = sm.OLS(Y, X)
        results = model.fit()
        
        # Assign coefficients and p-value
        params = results.params
        if len(params) >= 4:
            alpha, beta, smb_coef, hml_coef = params[:4]
            constant = params[4] if len(params) == 5 else float('NaN')
        else:
            alpha, beta, smb_coef, hml_coef, constant = (float('NaN'),) * 5
        alpha_pvalue = results.pvalues[0]
        
    # Append the results to the lists
    stocks.append(stock)
    alphas.append(alpha)
    betas.append(beta)
    smb_coefs.append(smb_coef)
    hml_coefs.append(hml_coef)
    RSQ.append(results.rsquared if not combined_returns.empty else float('NaN'))
    alpha_pvalues.append(alpha_pvalue)

# Create a DataFrame from the results
FF3_20 = pd.DataFrame({'Fund': stocks, 'Alpha': alphas, 'Market Beta': betas, 'SMB Coef': smb_coefs, 'HML Coef': hml_coefs,
                      'R-Squared': RSQ, 'p-value a': alpha_pvalues})

# Round the p-values to a reasonable number of decimal places (e.g., 5)
FF3_20['p-value a'] = FF3_20['p-value a'].round(5)
# Print the results
FF3_20

,Fund,Alpha,Market Beta,SMB Coef,HML Coef,R-Squared,p-value a
0,Mutual Fund Excess Returns,0.000014,0.940634,0.00013,0.000137,0.987031,0.0
1,ETF Excess Returns,0.000002,0.967076,0.00041,-0.000086,0.992853,0.0